apiVersion: apps/v1
kind: Deployment
metadata:
  name: "Testname"-deployment # nginx-deployment
spec:
  selector:
    matchLabels:
      app: Testname #nginx
  replicas: 2 ## tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: Testname #nginx
    spec:
      containers:
      - name: Testname #nginx
        image: Testname:1.0333 SNAPSHOT #nginx:1.14.2
	#?command: Testname[]
        ports:
        - containerPort: 80 #{containerPort}